name: "Ci (Entrega/Delivery Continua): Main Workflow"

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [main, a1]

jobs:
  deploy:
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Deploy
        run: |
          yarn install
          yarn deploy:prod
