name: "Ci (Integração Continua): Main Workflow"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Linter
        run: yarn lint
